project:
  type: website
  output-dir: docs

website:
  title: "Andrea Tentner, Ph.D."
  navbar:
    right:
      - text: Home
        href: index.qmd 
      - text: Blog
        href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



