# .github/workflows/preview.yml
# https://github.com/marketplace/actions/deploy-pr-preview
name: Deploy PR previews
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    paths:
      - "docs/**"
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # deployment strategy is currently to run quarto render locally to docs folder, add/commit/push updates to docs folder, so don't need to build after the push/pr
      # - name: Install and Build
      #   if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
      #   run: |
      #     npm install
      #     npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs
          preview-branch: main
          umbrella-dir: docs/pr-preview
          pages-base-path: docs
          qr-code: true
